language: cpp
group: travis_latest
sudo: false
cache: ccache
script: cmake

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    #- os: linux
      #addons:
        #apt:
          #sources:
            #- llvm-toolchain-trusty-5.0
          #packages:
            #- clang-5.0
      #env:
        #- MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo pip install cmake
  - which $CXX
  - $CXX --version
  - which $CC
  - $CC --version
  - which cmake
  - cmake --version

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - cmake --build . -- -j2
