language: cpp
group: travis_latest
sudo: false
cache: ccache
script: cmake

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qt5-default
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    #- os: linux
      #addons:
        #apt:
          #sources:
            #- llvm-toolchain-trusty-5.0
          #packages:
            #- clang-5.0
      #env:
        #- MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo pip install cmake
  - which $CXX
  - $CXX --version
  - which $CC
  - $CC --version
  - which cmake
  - cmake --version
  - which moc
  - moc --version

before_script:
- ls -lah
- mkdir -p build/{debug,release}
- cd build/debug
- cmake -DCMAKE_BUILD_TYPE=Debug -DSPAGHETTI_BUNDLE_JSON=ON -DSPAGHETTI_BUNDLE_SPDLOG=ON ../..
- cd ../release
- cmake -DCMAKE_BUILD_TYPE=Release -DSPAGHETTI_BUNDLE_JSON=ON -DSPAGHETTI_BUNDLE_SPDLOG=ON ../..
- cd ..

script:
  - cd debug
  - cmake --build . -- -j2
  - cd ../release
  - cmake --build . -- -j2
