version: 18.5.30.{build}
image: Visual Studio 2017
test: off

configuration:
- Release
- Debug

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive

before_build:
- cmd: >-
    mkdir build

    cd build

    cmake --version

    cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2017_64 -DSPAGHETTI_BUNDLE_JSON=ON -DSPAGHETTI_BUNDLE_SPDLOG=ON

build:
  project: c:\projects\spaghetti\build\Spaghetti.sln
  verbosity: minimal
  parallel: true
